id: AA9500745
title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
type: translation
pechas:
- IFB615B03
- I26477A86
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:02.926794
  last_modified_at: 2023-01-04 12:38:02.926803
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IFB615B03/47E3: '3233'
  I26477A86/1EEC: '3233'
